### ISSUE TITLE
Incorrect use of statics?

### ISSUE THREAD

**Issue by archfrog** [davidsblog/dweb#1]
Hi,

I just skimmed your source code and ran across a comment that says something to the effect that "static will initialize them to zeroes".  This is true, but there's a huge problem in using static in multi-threaded applications: Static basically tells the compiler to only allocate a SINGLE, GLOBAL copy of the variables so if you have multiple threads running, they'll be fighting each other as they all update the same global instance of the variable.  As a rule of thumb, you should never use static in MT apps, unless you are computing a constant that is only updated once at startup.

Cheers,
Mikael

**Comment by davidsblog** [comment]
Thanks.  I inherited those lines from [nweb](http://www.ibm.com/developerworks/systems/library/es-nweb/) which was multi-process.  But I have since added threading as an option.  I'll have a look...  The **serv_addr** might not make any difference as static because it's only assigned once before any other threads are created, and I don't think the value is ever changed.  The other one, **cli_addr** (passed to "accept" as a pointer) is _also_ only used on the main listening thread, before requests are handed off to separate threads for processing. 

But ... this does mean that you can't spin up different instances of dweb on different threads and have several webservers on different ports.  I didn't think about anybody wanting to do that (and I haven't tried it myself).  But that might be a good reason to not make these two variables static...

Thanks for pointing that out, I appreciate your help.

**Comment by davidsblog** [comment]
OK, these two variables are no longer static, _just in case_ somebody wants to try running more than one instance of dweb on different threads.  Although I haven't tried it.
